from tkinter import *
from random import randrange
from turtle import title

top =  Tk()
top.geometry("310x378+459+108")
top.minsize(120, 1)
top.maxsize(1370, 729)
top.resizable(1,  1)
top.title("Random Spin")
top.configure(borderwidth="2")
top.configure(background="#3e9ccb")
top.configure(highlightthickness="3")

selectedButton = IntVar()
lst = []
var = IntVar()
                                   
def But_1():
    lst.append(Entry1.get())
    Entry1.delete(0,END)
    Label1.configure(text='''Random Spin System''')
    Label4.configure(text='''''')
    Label4.configure(background="#3e9ccb")
    
def But_2():
    lst.remove(Entry1.get())
    Entry1.delete(0, END)
    Label1.configure(text='''Random Spin System''')
    Label4.configure(text='''''')
    Label4.configure(background="#3e9ccb")
    
def But_3():
    winner = randrange(0,len(lst))    
    Label1.configure(text=lst[winner])
    Label4.configure(background="#f2ea4f")
    Label4.configure(text='''Winner''')
    if var.get():
        lst.remove(lst[winner])
        
top.bind('<Return>',lambda event:But_1())

Entry1 = Entry(top)
Entry1.place(relx=0.101, rely=0.291, height=50, relwidth=0.785)
Entry1.configure(background="white")
Entry1.configure(disabledforeground="#a3a3a3")
Entry1.configure(font="TkFixedFont")
Entry1.configure(foreground="#000000")
Entry1.configure(insertbackground="black")


Button1 = Button(top)
Button1.place(relx=0.101, rely=0.476, height=34, width=107)
Button1.configure(activebackground="beige")
Button1.configure(activeforeground="black")
Button1.configure(background="#3e9ccb")
Button1.configure(command=But_1)
Button1.configure(compound='left')
Button1.configure(disabledforeground="#a3a3a3")
Button1.configure(foreground="#000000")
Button1.configure(highlightbackground="#d9d9d9")
Button1.configure(highlightcolor="black")
Button1.configure(pady="0")
Button1.configure(text='''APPEND''')

Button2 = Button(top)
Button2.place(relx=0.53, rely=0.476, height=34, width=107)
Button2.configure(activebackground="beige")
Button2.configure(activeforeground="black")
Button2.configure(background="#3e9ccb")
Button2.configure(command=But_2)
Button2.configure(compound='left')
Button2.configure(cursor="fleur")
Button2.configure(disabledforeground="#a3a3a3")
Button2.configure(foreground="#000000")
Button2.configure(highlightbackground="#d9d9d9")
Button2.configure(highlightcolor="black")
Button2.configure(pady="0")
Button2.configure(text='''DELETE''')
Button2.bind('<Return>')

Button3 = Button(top)
Button3.place(relx=0.101, rely=0.608, height=44, width=237)
Button3.configure(activebackground="beige")
Button3.configure(activeforeground="black")
Button3.configure(background="#3e9ccb")
Button3.configure(command=But_3)
Button3.configure(compound='left')
Button3.configure(disabledforeground="#a3a3a3")
Button3.configure(foreground="#000000")
Button3.configure(highlightbackground="#d9d9d9")
Button3.configure(highlightcolor="black")
Button3.configure(pady="0")
Button3.configure(text='''SPIN''')

Checkbutton1 = Checkbutton(top)
Checkbutton1.place(relx=0.034, rely=0.767, relheight=0.066, relwidth=0.899)
Checkbutton1.configure(activebackground="beige")
Checkbutton1.configure(activeforeground="black")
Checkbutton1.configure(anchor='w')
Checkbutton1.configure(background="#3e9ccb")
Checkbutton1.configure(compound='left')
Checkbutton1.configure(disabledforeground="#a3a3a3")
Checkbutton1.configure(foreground="#000000")
Checkbutton1.configure(highlightbackground="#d9d9d9")
Checkbutton1.configure(highlightcolor="black")
Checkbutton1.configure(justify='left')
Checkbutton1.configure(selectcolor="#d9d9d9")
Checkbutton1.configure(text='''Delete Winner Name Automaticaly After SPIN''')
Checkbutton1.configure(variable=var,onvalue = 1, offvalue = 0, )

menubar = Menu(top,font="TkMenuFont",bg='#74b5cd',fg='black')

Label1 = Label(top)
Label1.place(relx=0.101, rely=0.026, height=61, width=234)
Label1.configure(anchor='w')
Label1.configure(background="#3e9ccb")
Label1.configure(compound='left')
Label1.configure(cursor="fleur")
Label1.configure(disabledforeground="#a3a3a3")
Label1.configure(font="-family {Simplex_IV50} -size 14")
Label1.configure(foreground="#000000")
Label1.configure(text='''Random Spin System''')
Label2 = Label(top)
Label2.place(relx=0.671, rely=0.926, height=21, width=84)
Label2.configure(anchor='w')
Label2.configure(background="#3e9ccb")
Label2.configure(compound='left')
Label2.configure(disabledforeground="#a3a3a3")
Label2.configure(font="-family {ScriptC} -size 9")
Label2.configure(foreground="#000000")
Label2.configure(text='''Luban Mahfuz''')
Label3 = Label(top)
Label3.place(relx=0.101, rely=0.212, height=21, width=124)
Label3.configure(anchor='w')
Label3.configure(background="#3e9ccb")
Label3.configure(compound='left')
Label3.configure(cursor="fleur")
Label3.configure(disabledforeground="#a3a3a3")
Label3.configure(foreground="#000000")
Label3.configure(text='''Enter KeyWord Here:''')
Label4 = Label(top)
Label4.place(relx=0.805, rely=0.026, height=21, width=44)
Label4.configure(activebackground="#f2ea4f")
Label4.configure(anchor='w')
Label4.configure(background="#3e9ccb")
Label4.configure(compound='left')
Label4.configure(disabledforeground="#a3a3a3")
Label4.configure(foreground="#000000")
Label4.configure(text='''''')

top.mainloop()