#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Jul 30, 2022 09:40:27 PM +06  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 2 -menu "$top.m51" -background #3e9ccb \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -highlightthickness 3 
    wm focusmodel $top passive
    wm geometry $top 298x378+443+168
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 729
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 234 
    vTcl:DefineAlias "$top.ent46" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #3e9ccb -command But_1 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text APPEND 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #3e9ccb -command But_2 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DELETE 
    vTcl:DefineAlias "$top.but48" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #3e9ccb -command But_3 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text SPIN 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad50 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background #3e9ccb -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 \
        -text {Delete Winner Name Automaticaly After SPIN} \
        -variable selectedButton 
    vTcl:DefineAlias "$top.rad50" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m51 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #74b5cd -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #3e9ccb -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Simplex_IV50 -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Random Spin System} 
    vTcl:DefineAlias "$top.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #3e9ccb -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family ScriptC -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Luban Mahfuz} 
    vTcl:DefineAlias "$top.lab53" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #3e9ccb -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Enter KeyWord Here:} 
    vTcl:DefineAlias "$top.lab54" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f2ea4f -activeforeground SystemButtonText \
        -anchor w -background #f2ea4f -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Winner 
    vTcl:DefineAlias "$top.lab46" "Label4" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent46 \
        -in $top -x 0 -relx 0.102 -y 0 -rely 0.291 -width 234 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.101 -y 0 -rely 0.476 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.53 -y 0 -rely 0.476 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.101 -y 0 -rely 0.608 -width 237 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.rad50 \
        -in $top -x 0 -relx 0.034 -y 0 -rely 0.767 -width 0 -relwidth 0.899 \
        -height 0 -relheight 0.066 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.101 -y 0 -rely 0.026 -width 0 -relwidth 0.785 \
        -height 0 -relheight 0.161 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.671 -y 0 -rely 0.926 -width 0 -relwidth 0.282 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.101 -y 0 -rely 0.212 -width 0 -relwidth 0.416 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.805 -y 0 -rely 0.026 -width 0 -relwidth 0.148 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

